version: '3'
services:
  postgres:
    image: postgres:16.2
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jefad
      POSTGRES_PASSWORD: jef123
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
